targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: vi
          fallback_strategy: base_locale
          input_directory: lib/i18n
          output_directory: lib/i18n
          output_format: single_file
          locale_handling: true
