// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8763zUxG2aiAMsk8A_MFiZjpZWeD-R3w',
    appId: '1:531765551090:web:1078c76f41c55b6982556b',
    messagingSenderId: '531765551090',
    projectId: 'smart-interview-6b5c1',
    authDomain: 'smart-interview-6b5c1.firebaseapp.com',
    storageBucket: 'smart-interview-6b5c1.firebasestorage.app',
    measurementId: 'G-X1BKS64RCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFeous5u4pMXUHilRisOcx94I43NLlB8',
    appId: '1:531765551090:android:354fcd0dd376f95182556b',
    messagingSenderId: '531765551090',
    projectId: 'smart-interview-6b5c1',
    storageBucket: 'smart-interview-6b5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkMughZWBCZ6jkV7hMPjnkyJNR9vAF5M',
    appId: '1:531765551090:ios:d533290c61751d6d82556b',
    messagingSenderId: '531765551090',
    projectId: 'smart-interview-6b5c1',
    storageBucket: 'smart-interview-6b5c1.firebasestorage.app',
    iosBundleId: 'com.ntc.smartInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkMughZWBCZ6jkV7hMPjnkyJNR9vAF5M',
    appId: '1:531765551090:ios:93d0b55f5f77c6b282556b',
    messagingSenderId: '531765551090',
    projectId: 'smart-interview-6b5c1',
    storageBucket: 'smart-interview-6b5c1.firebasestorage.app',
    iosBundleId: 'com.example.smartInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8763zUxG2aiAMsk8A_MFiZjpZWeD-R3w',
    appId: '1:531765551090:web:967c51620827fe5482556b',
    messagingSenderId: '531765551090',
    projectId: 'smart-interview-6b5c1',
    authDomain: 'smart-interview-6b5c1.firebaseapp.com',
    storageBucket: 'smart-interview-6b5c1.firebasestorage.app',
    measurementId: 'G-EWQZ0Q1HD9',
  );
}
